spring.application.name=DSAClock

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dsaClock
spring.datasource.username=postgres
spring.datasource.password=Atanu@2005

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect